### ISSUE TITLE
feature request/idea: downloading postgres

### ISSUE THREAD

**Issue by karelbilek** [rubenv/pgtest#2]
There is this project, which creates lightweight postgres binaries (called "embedded" for some reason)

https://github.com/zonkyio/embedded-postgres-binaries

It's some Java stuff, but there is this go package that uses those binaries and automatically downloads them

https://github.com/fergusstrange/embedded-postgres

Now I don't like that package code or API at all (for many reasons), but the idea is good, and I think it's possible to pick the good ideas from there and use it in this package.

I'm thinking of doing a fork and maybe eventually doing a PR here. (Or keeping it in a fork.) I like that you don't need to even install anything, which makes set up easier - we spent some time with a colleague debugging some random permission issue with already existing local postgres. But it makes the API more complex and introduces lot of new stuff that needs to be maintained (getting the code from maven, un-zipping it, doing some magic there).

**Comment by rubenv** [comment]
@karelbilek I'd like to keep this package simple, but what you describe can perfectly be implemented as a wrapper package: one that downloads the binaries and then just uses `pgtest`.

Would that work?

**Comment by karelbilek** [comment]
yeah
