### ISSUE TITLE
Fails on Mac OS X 14.3.1

### ISSUE THREAD

**Issue by molguin92** [rubenv/pgtest#3]
This is a great little library, thanks! It works perfectly in containers and bare-metal Linux environments, and has made our testing so much more streamlined.

However, I have noticed that it does not seem to work on Mac OS X. On an environment with PostgreSQL 16.2:

```
$> which postgres 
/opt/homebrew/bin/postgres

$> postgres --version        
postgres (PostgreSQL) 16.2 (Homebrew)
```

`pgtest.Start()` returns the following error:

```
Failed to prepare test DB: dial unix /var/folders/v3/rwb_fz_54x920ydszrlcxw1m0000gn/T/pgtest4289357232/sock/.s.PGSQL.5432: connect: no such file or directory
```

My guess is that temporary directories and files somehow work differently in Mac.

**Comment by rubenv** [comment]
I don't have a (recent) Mac at hand to test things but will happily accept a pull request.

**Comment by molguin92** [comment]
Sure thing! See https://github.com/rubenv/pgtest/pull/4
